!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!      
!M
!M
!M
MODULE  ioroutines
  !
  IMPLICIT NONE
  PUBLIC
  !

!  file_target_energies = 'dat/en1e.dat'


CONTAINS

 SUBROUTINE hfile(n, sdir, sfile, mode, i1)
   IMPLICIT NONE
   !
   INTEGER                  n
   CHARACTER( LEN = * )   sdir, sfile
   CHARACTER( LEN = * )   mode
   INTEGER                  i1
   !
   CHARACTER( LEN = 100 )   outfile
   CHARACTER( LEN = 6   )   s1

   !xxxxxxxxxxxx

   WRITE(s1,'(i6)') i1
      
   outfile = sdir//"/"//sfile//"-"//TRIM(ADJUSTL(S1))//"."//sdir
      
   IF(mode=='bin') THEN
      OPEN(n, file=outfile, form='UNFORMATTED',access='SEQUENTIAL')
   ELSE IF(mode=='ascii') THEN
      OPEN(n, file=outfile)
   ENDIF
   
   WRITE(*,'(a10,10x,2a40)') '# hfile::','  opened file = ', outfile
   
   RETURN
 END SUBROUTINE hfile
!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 SUBROUTINE    cfile(n, sdir, sfile,i1)
   IMPLICIT NONE
   !
   INTEGER                  n
   CHARACTER( LEN = * )   sdir, sfile
   INTEGER                  i1
   !
   CHARACTER( LEN = 100 )   outfile
   CHARACTER( LEN = 6   )   s1

   !xxxxxxxxxxxx

   WRITE(s1,'(i6)') i1
      
   outfile = sdir//"/"//sfile//"-"//TRIM(ADJUSTL(S1))//"."//sdir
      
   OPEN(n, file=outfile)
   
   WRITE(*,'(a10,10x,2a40)') '# cfile::','  opened file = ', outfile
   
   RETURN
 END SUBROUTINE CFILE
!xxxxxxxxxxxxxxxxxxxxxxxxxxx
 SUBROUTINE DMXFILE(n, sdir, sfile, mode, gauge , i1, i2)

   IMPLICIT NONE
   !
   INTEGER                  n
   CHARACTER( LEN = * )   sdir, sfile
   CHARACTER( LEN = * )   mode, gauge 
   INTEGER                  i1,i2
   !
   CHARACTER( LEN = 100 )   outfile
   CHARACTER( LEN = 6   )   s1, s2

   !xxxxxxxxxxxx

   WRITE(s1,'(i6)') i1
   WRITE(s2,'(i6)') i2

      
      outfile = sdir//"/"//sfile//"-"//&
           &TRIM(ADJUSTL(GAUGE))//TRIM(ADJUSTL(S1))//TRIM(ADJUSTL(S2))//&
           &"."//sdir
      
   IF(mode=='bin') THEN
      OPEN(n, file=outfile, form='UNFORMATTED',access='SEQUENTIAL')
   ELSE IF(mode=='ascii') THEN
      OPEN(n, file=outfile)
   ENDIF
   
  WRITE(*,'(a10,10x,2a40)') '# dfile::','  opened file = ', outfile

   RETURN
 END SUBROUTINE DMXFILE

 !xxxxxxxx
 
 
!!!###############################################
  SUBROUTINE D1EFILE(N, L)
    !
    IMPLICIT NONE
    INTEGER N,L
    
!    WRITE(*,*) '# d1efile::                           L = ', L
          
    IF(L.EQ.0) OPEN(N,FILE='dat/d1e-0.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.1) OPEN(N,FILE='dat/d1e-1.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.2) OPEN(N,FILE='dat/d1e-2.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.3) OPEN(N,FILE='dat/d1e-3.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.4) OPEN(N,FILE='dat/d1e-4.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.5) OPEN(N,FILE='dat/d1e-5.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.6) OPEN(N,FILE='dat/d1e-6.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.7) OPEN(N,FILE='dat/d1e-7.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.8) OPEN(N,FILE='dat/d1e-8.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.9) OPEN(N,FILE='dat/d1e-9.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.10) OPEN(N,FILE='dat/d1e-10.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.11) OPEN(N,FILE='dat/d1e-11.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    RETURN
  END SUBROUTINE D1EFILE
!!!#####################################################################
 
  SUBROUTINE COREFILE(N, L)
    IMPLICIT NONE
    INTEGER N,L
    WRITE(*,*) '# corefile::                          L = ', L
    
    IF(L.EQ.0) OPEN(N,FILE='dat/core-0.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.1) OPEN(N,FILE='dat/core-1.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.2) OPEN(N,FILE='dat/core-2.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.3) OPEN(N,FILE='dat/core-3.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    
    RETURN
  END SUBROUTINE COREFILE
!!!#####################################################################
  SUBROUTINE HMXFILE(N, L)
    IMPLICIT NONE
    INTEGER N,L
    
    WRITE(*,*) '# hmxfile::                           L = ', L
    
    IF(L.EQ.0) OPEN(N,FILE='DAT/HMX-0.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.1) OPEN(N,FILE='DAT/HMX-1.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.2) OPEN(N,FILE='DAT/HMX-2.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.3) OPEN(N,FILE='DAT/HMX-3.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.4) OPEN(N,FILE='DAT/HMX-4.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.5) OPEN(N,FILE='DAT/HMX-5.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.6) OPEN(N,FILE='DAT/HMX-6.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.7) OPEN(N,FILE='DAT/HMX-7.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.8) OPEN(N,FILE='DAT/HMX-8.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.9) OPEN(N,FILE='DAT/HMX-9.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.10) OPEN(N,FILE='DAT/HMX-10.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.11) OPEN(N,FILE='DAT/HMX-11.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    RETURN
  END SUBROUTINE HMXFILE
!!!#####################################################################
  SUBROUTINE BMXFILE(N, L)
    IMPLICIT NONE
    INTEGER N,L
    
!    WRITE(*,*) '# bmxfile::                            L = ', L
    
    IF(L.EQ.0) OPEN(N,FILE='DAT/BMX-0.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.1) OPEN(N,FILE='DAT/BMX-1.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.2) OPEN(N,FILE='DAT/BMX-2.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.3) OPEN(N,FILE='DAT/BMX-3.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.4) OPEN(N,FILE='DAT/BMX-4.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.5) OPEN(N,FILE='DAT/BMX-5.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.6) OPEN(N,FILE='DAT/BMX-6.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.7) OPEN(N,FILE='DAT/BMX-7.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.8) OPEN(N,FILE='DAT/BMX-8.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.9) OPEN(N,FILE='DAT/BMX-9.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.10) OPEN(N,FILE='DAT/BMX-10.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    IF(L.EQ.11) OPEN(N,FILE='DAT/BMX-11.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
    RETURN
  END SUBROUTINE BMXFILE
!!!#####################################################################
  SUBROUTINE HR12FILE(N, L)
    IMPLICIT NONE
    INTEGER N,L
    
    IF(L.GT.14) THEN
       WRITE(*,*) '# hr12file::              L  > 14. Stop'
       WRITE(*,*) '# hr12file::                      L  = ',L
       STOP
      ELSE
         WRITE(*,*) '# hr12file::                       L = ', L
      ENDIF
         
      IF(L.EQ.0) OPEN(N,FILE='DAT/HR12-0.DAT',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.1) OPEN(N,FILE='DAT/HR12-1.DAT',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.2) OPEN(N,FILE='DAT/HR12-2.DAT',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.3) OPEN(N,FILE='DAT/HR12-3.DAT',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.4) OPEN(N,FILE='DAT/HR12-4.DAT',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.5) OPEN(N,FILE='DAT/HR12-5.DAT',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.6) OPEN(N,FILE='DAT/HR12-6.DAT',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.7) OPEN(N,FILE='DAT/HR12-7.DAT',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.8) OPEN(N,FILE='DAT/HR12-8.DAT',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.9) OPEN(N,FILE='DAT/HR12-9.DAT',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.10) OPEN(N,FILE='DAT/HR12-10.DAT',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.11) OPEN(N,FILE='DAT/HR12-11.DAT',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.12) OPEN(N,FILE='DAT/HR12-12.DAT',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.13) OPEN(N,FILE='DAT/HR12-13.DAT',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.14) OPEN(N,FILE='DAT/HR12-14.DAT',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      RETURN
    
    END SUBROUTINE HR12FILE

!!!#######################################################################
  SUBROUTINE HCFGFILE(N, L)
    IMPLICIT NONE
    INTEGER N, L
!!!........................


    WRITE(*,*) '# hcfgfile::                       L = ', L

    IF(L.EQ.0) OPEN(N,FILE='INP/CFG-0.INP')
    IF(L.EQ.1) OPEN(N,FILE='INP/CFG-1.INP')
    IF(L.EQ.2) OPEN(N,FILE='INP/CFG-2.INP')
    IF(L.EQ.3) OPEN(N,FILE='INP/CFG-3.INP')
    IF(L.EQ.4) OPEN(N,FILE='INP/CFG-4.INP')
    IF(L.EQ.5) OPEN(N,FILE='INP/CFG-5.INP')
    IF(L.EQ.6) OPEN(N,FILE='INP/CFG-6.INP')
    IF(L.EQ.7) OPEN(N,FILE='INP/CFG-7.INP')
    IF(L.EQ.8) OPEN(N,FILE='INP/CFG-8.INP')
    IF(L.EQ.9) OPEN(N,FILE='INP/CFG-9.INP')
    IF(L.EQ.10) OPEN(N,FILE='INP/CFG-10.INP')
    IF(L.EQ.11) OPEN(N,FILE='INP/CFG-11.INP')
    IF(L.EQ.12) OPEN(N,FILE='INP/CFG-12.INP')
    IF(L.EQ.13) OPEN(N,FILE='INP/CFG-13.INP')
    IF(L.EQ.14) OPEN(N,FILE='INP/CFG-14.INP')

    RETURN
  END SUBROUTINE HCFGFILE
!!!#######################################################################
  SUBROUTINE CFGFILE(N, L)
    IMPLICIT NONE
    INTEGER N, L
!!!........................


    WRITE(*,*) '# cfgfile::                             L = ', L

    
    IF(L.EQ.0) OPEN(N,FILE='inp/cfg-0.inp')
    IF(L.EQ.1) OPEN(N,FILE='inp/cfg-1.inp')
    IF(L.EQ.2) OPEN(N,FILE='inp/cfg-2.inp')
    IF(L.EQ.3) OPEN(N,FILE='inp/cfg-3.inp')
    IF(L.EQ.4) OPEN(N,FILE='inp/cfg-4.inp')
    IF(L.EQ.5) OPEN(N,FILE='inp/cfg-5.inp')
    IF(L.EQ.6) OPEN(N,FILE='inp/cfg-6.inp')
    IF(L.EQ.7) OPEN(N,FILE='inp/cfg-7.inp')
    IF(L.EQ.8) OPEN(N,FILE='inp/cfg-8.inp')
    IF(L.EQ.9) OPEN(N,FILE='inp/cfg-9.inp')
    IF(L.EQ.10) OPEN(N,FILE='inp/cfg-10.inp')
    IF(L.EQ.11) OPEN(N,FILE='inp/cfg-11.inp')
    IF(L.EQ.12) OPEN(N,FILE='inp/cfg-12.inp')
    IF(L.EQ.13) OPEN(N,FILE='inp/cfg-13.inp')
    IF(L.EQ.14) OPEN(N,FILE='inp/cfg-14.inp')

    RETURN
  END SUBROUTINE CFGFILE
!!!#####################################################################
  SUBROUTINE H2EFILE(N, L)
    IMPLICIT NONE
    INTEGER N,L


       WRITE(*,*) '# h2efile::                          L = ', L
    
    IF(N.EQ.1.OR.N.EQ.2) THEN 

       WRITE(*,*) '# h2efile::             single ionization'

       IF(L.EQ.0) OPEN(N,FILE='DAT/H2ES-0.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.1) OPEN(N,FILE='DAT/H2ES-1.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.2) OPEN(N,FILE='DAT/H2ES-2.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.3) OPEN(N,FILE='DAT/H2ES-3.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.4) OPEN(N,FILE='DAT/H2ES-4.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.5) OPEN(N,FILE='DAT/H2ES-5.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.6) OPEN(N,FILE='DAT/H2ES-6.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.7) OPEN(N,FILE='DAT/H2ES-7.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.8) OPEN(N,FILE='DAT/H2ES-8.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.9) OPEN(N,FILE='DAT/H2ES-9.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.10) OPEN(N,FILE='DAT/H2ES-10.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.11) OPEN(N,FILE='DAT/H2ES-11.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       
    ELSE

       WRITE(*,*) '# h2efile::             double ionization'

       IF(L.EQ.0) OPEN(N,FILE='DAT/H2ED-0.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.1) OPEN(N,FILE='DAT/H2ED-1.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.2) OPEN(N,FILE='DAT/H2ED-2.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.3) OPEN(N,FILE='DAT/H2ED-3.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.4) OPEN(N,FILE='DAT/H2ED-4.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.5) OPEN(N,FILE='DAT/H2ED-5.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.6) OPEN(N,FILE='DAT/H2ED-6.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.7) OPEN(N,FILE='DAT/H2ED-7.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.8) OPEN(N,FILE='DAT/H2ED-8.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.9) OPEN(N,FILE='DAT/H2ED-9.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.10) OPEN(N,FILE='DAT/H2ED-10.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       IF(L.EQ.11) OPEN(N,FILE='DAT/H2ED-11.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
       
    ENDIF


    RETURN
  END SUBROUTINE H2EFILE
!!!#####################################################################
  SUBROUTINE AMXFILE(N, L)
    IMPLICIT NONE
    INTEGER N,L
        
    IF(N.EQ.10.OR.N.EQ.11) THEN 


       WRITE(*,*) '# amxfile::                       L = ', L
       WRITE(*,*) '# amxfile::          single ionization'


       IF(L.EQ.0) OPEN(N, FILE='DAT/AMXS-0.DAT')
       IF(L.EQ.1) OPEN(N, FILE='DAT/AMXS-1.DAT')
       IF(L.EQ.2) OPEN(N, FILE='DAT/AMXS-2.DAT')
       IF(L.EQ.3) OPEN(N, FILE='DAT/AMXS-3.DAT')
       IF(L.EQ.4) OPEN(N, FILE='DAT/AMXS-4.DAT')
       IF(L.EQ.5) OPEN(N, FILE='DAT/AMXS-5.DAT')
       IF(L.EQ.6) OPEN(N, FILE='DAT/AMXS-6.DAT')
       IF(L.EQ.7) OPEN(N, FILE='DAT/AMXS-7.DAT')
       IF(L.EQ.8) OPEN(N, FILE='DAT/AMXS-8.DAT')
       IF(L.EQ.9) OPEN(N, FILE='DAT/AMXS-9.DAT')
       IF(L.EQ.10) OPEN(N,FILE='DAT/AMXS-10.DAT')
       IF(L.EQ.11) OPEN(N,FILE='DAT/AMXS-11.DAT')
       
    ELSE


       WRITE(*,*) '# amxfile::                       L = ', L
       WRITE(*,*) '# amxfile::          double ionization'


       IF(L.EQ.0) OPEN(N, FILE='DAT/AMXD-0.DAT')
       IF(L.EQ.1) OPEN(N, FILE='DAT/AMXD-1.DAT')
       IF(L.EQ.2) OPEN(N, FILE='DAT/AMXD-2.DAT')
       IF(L.EQ.3) OPEN(N, FILE='DAT/AMXD-3.DAT')
       IF(L.EQ.4) OPEN(N, FILE='DAT/AMXD-4.DAT')
       IF(L.EQ.5) OPEN(N, FILE='DAT/AMXD-5.DAT')
       IF(L.EQ.6) OPEN(N, FILE='DAT/AMXD-6.DAT')
       IF(L.EQ.7) OPEN(N, FILE='DAT/AMXD-7.DAT')
       IF(L.EQ.8) OPEN(N, FILE='DAT/AMXD-8.DAT')
       IF(L.EQ.9) OPEN(N, FILE='DAT/AMXD-9.DAT')
       IF(L.EQ.10) OPEN(N,FILE='DAT/AMXD-10.DAT')
       IF(L.EQ.11) OPEN(N,FILE='DAT/AMXD-11.DAT')
       


    ENDIF

    RETURN
  END SUBROUTINE AMXFILE

!!!#####################################################################
    SUBROUTINE KMXFILE(N, L)
      IMPLICIT NONE
      INTEGER N,L
      
      IF(N.EQ.20.OR.N.EQ.21) THEN 


       WRITE(*,*) '# kmxfile::                       L = ', L
       WRITE(*,*) '# kmxfile::          single ionization'


       IF(L.EQ.0) OPEN(N, FILE='DAT/KMXS-0.DAT')
       IF(L.EQ.1) OPEN(N, FILE='DAT/KMXS-1.DAT')
       IF(L.EQ.2) OPEN(N, FILE='DAT/KMXS-2.DAT')
       IF(L.EQ.3) OPEN(N, FILE='DAT/KMXS-3.DAT')
       IF(L.EQ.4) OPEN(N, FILE='DAT/KMXS-4.DAT')
       IF(L.EQ.5) OPEN(N, FILE='DAT/KMXS-5.DAT')
       IF(L.EQ.6) OPEN(N, FILE='DAT/KMXS-6.DAT')
       IF(L.EQ.7) OPEN(N, FILE='DAT/KMXS-7.DAT')
       IF(L.EQ.8) OPEN(N, FILE='DAT/KMXS-8.DAT')
       IF(L.EQ.9) OPEN(N, FILE='DAT/KMXS-9.DAT')
       IF(L.EQ.10) OPEN(N,FILE='DAT/KMXS-10.DAT')
       IF(L.EQ.11) OPEN(N,FILE='DAT/KMXS-11.DAT')
         
      ELSE

       WRITE(*,*) '# kmxfile::                       L = ', L
       WRITE(*,*) '# kmxfile::          double ionization'


       IF(L.EQ.0) OPEN(N, FILE='DAT/KMXD-0.DAT')
       IF(L.EQ.1) OPEN(N, FILE='DAT/KMXD-1.DAT')
       IF(L.EQ.2) OPEN(N, FILE='DAT/KMXD-2.DAT')
       IF(L.EQ.3) OPEN(N, FILE='DAT/KMXD-3.DAT')
       IF(L.EQ.4) OPEN(N, FILE='DAT/KMXD-4.DAT')
       IF(L.EQ.5) OPEN(N, FILE='DAT/KMXD-5.DAT')
       IF(L.EQ.6) OPEN(N, FILE='DAT/KMXD-6.DAT')
       IF(L.EQ.7) OPEN(N, FILE='DAT/KMXD-7.DAT')
       IF(L.EQ.8) OPEN(N, FILE='DAT/KMXD-8.DAT')
       IF(L.EQ.9) OPEN(N, FILE='DAT/KMXD-9.DAT')
       IF(L.EQ.10) OPEN(N,FILE='DAT/KMXD-10.DAT')
       IF(L.EQ.11) OPEN(N,FILE='DAT/KMXD-11.DAT')
         
      ENDIF

      RETURN
    END SUBROUTINE KMXFILE

!!!#####################################################################
      SUBROUTINE ZMXFILE(N, L)
        IMPLICIT NONE
        INTEGER N,L
        
        IF(N.EQ.30.OR.N.EQ.31) THEN 


       WRITE(*,*) '# zmxfile::                       L = ', L
       WRITE(*,*) '# zmxfile::          single ionization'          

       IF(L.EQ.0) OPEN(N, FILE='DAT/ZMXS-0.DAT')
       IF(L.EQ.1) OPEN(N, FILE='DAT/ZMXS-1.DAT')
       IF(L.EQ.2) OPEN(N, FILE='DAT/ZMXS-2.DAT')
       IF(L.EQ.3) OPEN(N, FILE='DAT/ZMXS-3.DAT')
       IF(L.EQ.4) OPEN(N, FILE='DAT/ZMXS-4.DAT')
       IF(L.EQ.5) OPEN(N, FILE='DAT/ZMXS-5.DAT')
       IF(L.EQ.6) OPEN(N, FILE='DAT/ZMXS-6.DAT')
       IF(L.EQ.7) OPEN(N, FILE='DAT/ZMXS-7.DAT')
       IF(L.EQ.8) OPEN(N, FILE='DAT/ZMXS-8.DAT')
       IF(L.EQ.9) OPEN(N, FILE='DAT/ZMXS-9.DAT')
       IF(L.EQ.10) OPEN(N,FILE='DAT/ZMXS-10.DAT')
       IF(L.EQ.11) OPEN(N,FILE='DAT/ZMXS-11.DAT')
           
           
        ELSE
       WRITE(*,*) '# zmxfile::                       L = ', L
       WRITE(*,*) '# zmxfile::          double ionization'


       IF(L.EQ.0) OPEN(N, FILE='DAT/ZMXD-0.DAT')
       IF(L.EQ.1) OPEN(N, FILE='DAT/ZMXD-1.DAT')
       IF(L.EQ.2) OPEN(N, FILE='DAT/ZMXD-2.DAT')
       IF(L.EQ.3) OPEN(N, FILE='DAT/ZMXD-3.DAT')
       IF(L.EQ.4) OPEN(N, FILE='DAT/ZMXD-4.DAT')
       IF(L.EQ.5) OPEN(N, FILE='DAT/ZMXD-5.DAT')
       IF(L.EQ.6) OPEN(N, FILE='DAT/ZMXD-6.DAT')
       IF(L.EQ.7) OPEN(N, FILE='DAT/ZMXD-7.DAT')
       IF(L.EQ.8) OPEN(N, FILE='DAT/ZMXD-8.DAT')
       IF(L.EQ.9) OPEN(N, FILE='DAT/ZMXD-9.DAT')
       IF(L.EQ.10) OPEN(N,FILE='DAT/ZMXD-10.DAT')
       IF(L.EQ.11) OPEN(N,FILE='DAT/ZMXD-11.DAT')
           
        ENDIF


        RETURN
      END SUBROUTINE ZMXFILE

!!!#####################################################################
      SUBROUTINE RBBFILE(N, L)
        IMPLICIT NONE
        INTEGER N,L
        
        WRITE(*,*) '# rbbfile::             < B | R | B >  :', L

        IF(L.EQ.0) OPEN(N,FILE='DAT/RBB-0.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
        IF(L.EQ.1) OPEN(N,FILE='DAT/RBB-1.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
        IF(L.EQ.2) OPEN(N,FILE='DAT/RBB-2.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
        IF(L.EQ.3) OPEN(N,FILE='DAT/RBB-3.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
        IF(L.EQ.4) OPEN(N,FILE='DAT/RBB-4.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
        IF(L.EQ.5) OPEN(N,FILE='DAT/RBB-5.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
        IF(L.EQ.6) OPEN(N,FILE='DAT/RBB-6.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
        IF(L.EQ.7) OPEN(N,FILE='DAT/RBB-7.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
        IF(L.EQ.8) OPEN(N,FILE='DAT/RBB-8.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
        IF(L.EQ.9) OPEN(N,FILE='DAT/RBB-9.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
        IF(L.EQ.10) OPEN(N,FILE='DAT/RBB-10.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
        IF(L.EQ.11) OPEN(N,FILE='DAT/RBB-11.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
        IF(L.EQ.12) OPEN(N,FILE='DAT/RBB-12.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
        IF(L.EQ.13) OPEN(N,FILE='DAT/RBB-13.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
        IF(L.EQ.14) OPEN(N,FILE='DAT/RBB-14.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
        
        RETURN
      END SUBROUTINE RBBFILE

!!!##########################################################
      SUBROUTINE RWFBFILE(N, L1, L2, MODE)
        IMPLICIT NONE
        INTEGER N,L1,L2,MODE

      IF(L1.GT.14) THEN

         WRITE(*,*) '# rwfbfile::           L1,L2 > 14. STOP'
         WRITE(*,*) '# rwfbfile::                      L1 = ',L1 
         WRITE(*,*) '# rwfbfile::                      L2 = ',L2 
         STOP

      ELSE

         WRITE(*,*) '# rwfbfile ::           < WF | R | B > :', L1, L2

      ENDIF

      IF(MODE.EQ.0) THEN

      IF(L1.EQ.0.AND.L2.EQ.1) OPEN(N,FILE='DAT/RWFB-01.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.1.AND.L2.EQ.0) OPEN(N,FILE='DAT/RWFB-10.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.1.AND.L2.EQ.2) OPEN(N,FILE='DAT/RWFB-12.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.2.AND.L2.EQ.1) OPEN(N,FILE='DAT/RWFB-21.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.2.AND.L2.EQ.3) OPEN(N,FILE='DAT/RWFB-23.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.3.AND.L2.EQ.2) OPEN(N,FILE='DAT/RWFB-32.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.3.AND.L2.EQ.4)  OPEN(N,FILE='DAT/RWFB-34.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.4.AND.L2.EQ.3)  OPEN(N,FILE='DAT/RWFB-43.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.4.AND.L2.EQ.5)  OPEN(N,FILE='DAT/RWFB-45.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.5.AND.L2.EQ.4)  OPEN(N,FILE='DAT/RWFB-54.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.5.AND.L2.EQ.6)  OPEN(N,FILE='DAT/RWFB-56.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.6.AND.L2.EQ.5)  OPEN(N,FILE='DAT/RWFB-65.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.6.AND.L2.EQ.7)  OPEN(N,FILE='DAT/RWFB-67.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.7.AND.L2.EQ.6)  OPEN(N,FILE='DAT/RWFB-76.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.7.AND.L2.EQ.8)  OPEN(N,FILE='DAT/RWFB-78.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.8.AND.L2.EQ.7)  OPEN(N,FILE='DAT/RWFB-87.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.8.AND.L2.EQ.9)  OPEN(N,FILE='DAT/RWFB-89.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.9.AND.L2.EQ.8)  OPEN(N,FILE='DAT/RWFB-98.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.9.AND.L2.EQ.10) OPEN(N,FILE='DAT/RWFB-910.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.10.AND.L2.EQ.9) OPEN(N,FILE='DAT/RWFB-109.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.10.AND.L2.EQ.11) OPEN(N,FILE='DAT/RWFB-1011.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.11.AND.L2.EQ.10) OPEN(N,FILE='DAT/RWFB-1110.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.11.AND.L2.EQ.12) OPEN(N,FILE='DAT/RWFB-1112.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.12.AND.L2.EQ.11) OPEN(N,FILE='DAT/RWFB-1211.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.12.AND.L2.EQ.13) OPEN(N,FILE='DAT/RWFB-1213.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.13.AND.L2.EQ.12) OPEN(N,FILE='DAT/RWFB-1312.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.13.AND.L2.EQ.14) OPEN(N,FILE='DAT/RWFB-1314.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.4.AND.L2.EQ.13)  OPEN(N,FILE='DAT/RWFB-1415.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      ELSE
         
      IF(L1.EQ.0.AND.L2.EQ.1) OPEN(N,FILE='DAT/RWFB-01.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.1.AND.L2.EQ.0) OPEN(N,FILE='DAT/RWFB-10.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.1.AND.L2.EQ.2) OPEN(N,FILE='DAT/RWFB-12.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.2.AND.L2.EQ.1) OPEN(N,FILE='DAT/RWFB-21.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.2.AND.L2.EQ.3) OPEN(N,FILE='DAT/RWFB-23.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.3.AND.L2.EQ.2) OPEN(N,FILE='DAT/RWFB-32.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.3.AND.L2.EQ.4)   OPEN(N,FILE='DAT/RWFB-34.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.4.AND.L2.EQ.3)   OPEN(N,FILE='DAT/RWFB-43.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.4.AND.L2.EQ.5)   OPEN(N,FILE='DAT/RWFB-45.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.5.AND.L2.EQ.4)   OPEN(N,FILE='DAT/RWFB-54.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.5.AND.L2.EQ.6)   OPEN(N,FILE='DAT/RWFB-56.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.6.AND.L2.EQ.5)   OPEN(N,FILE='DAT/RWFB-65.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.6.AND.L2.EQ.7)   OPEN(N,FILE='DAT/RWFB-67.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.7.AND.L2.EQ.6)   OPEN(N,FILE='DAT/RWFB-76.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.7.AND.L2.EQ.8)   OPEN(N,FILE='DAT/RWFB-78.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.8.AND.L2.EQ.7)   OPEN(N,FILE='DAT/RWFB-87.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.8.AND.L2.EQ.9)   OPEN(N,FILE='DAT/RWFB-89.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.9.AND.L2.EQ.8)   OPEN(N,FILE='DAT/RWFB-98.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.9.AND.L2.EQ.10)  OPEN(N,FILE='DAT/RWFB-910.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.10.AND.L2.EQ.9)  OPEN(N,FILE='DAT/RWFB-109.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.10.AND.L2.EQ.11) OPEN(N,FILE='DAT/RWFB-1011.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.11.AND.L2.EQ.10) OPEN(N,FILE='DAT/RWFB-1110.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.11.AND.L2.EQ.12) OPEN(N,FILE='DAT/RWFB-1112.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.12.AND.L2.EQ.11) OPEN(N,FILE='DAT/RWFB-1211.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.12.AND.L2.EQ.13) OPEN(N,FILE='DAT/RWFB-1213.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.13.AND.L2.EQ.12) OPEN(N,FILE='DAT/RWFB-1312.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.13.AND.L2.EQ.14) OPEN(N,FILE='DAT/RWFB-1314.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.14.AND.L2.EQ.13)  OPEN(N,FILE='DAT/RWFB-1413.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

   ENDIF

   RETURN

 END SUBROUTINE RWFBFILE

!!!#########################################

      SUBROUTINE RWFBBFILE(N, L, MODE)
        IMPLICIT NONE
        INTEGER N,L,MODE

      IF(L.GT.14) THEN

         WRITE(*,*) '# rwfbfile ::           L1,L2 > 14. STOP'
         WRITE(*,*) '# rwfbfile ::                       L = ',L 
         STOP
         

      ELSE

         WRITE(*,*) '# rwfbbfile::           < WF | R | B > :', L, L+1

      ENDIF

      IF(MODE.EQ.0) THEN

      IF(L.EQ.0)  OPEN(N,FILE='DAT/RWFBB-01.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.1)  OPEN(N,FILE='DAT/RWFBB-12.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.2)  OPEN(N,FILE='DAT/RWFBB-23.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.3)  OPEN(N,FILE='DAT/RWFBB-34.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.4)  OPEN(N,FILE='DAT/RWFBB-45.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.5)  OPEN(N,FILE='DAT/RWFBB-56.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.6)  OPEN(N,FILE='DAT/RWFBB-67.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.7)  OPEN(N,FILE='DAT/RWFBB-78.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.8)  OPEN(N,FILE='DAT/RWFBB-89.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.9)  OPEN(N,FILE='DAT/RWFBB-910.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.10) OPEN(N,FILE='DAT/RWFBB-1011.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.11) OPEN(N,FILE='DAT/RWFBB-1112.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.12) OPEN(N,FILE='DAT/RWFBB-1213.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.13) OPEN(N,FILE='DAT/RWFBB-1314.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      ELSE

      IF(L.EQ.0)  OPEN(N,FILE='DAT/RWFBB-01.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.1)  OPEN(N,FILE='DAT/RWFBB-12.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.2)  OPEN(N,FILE='DAT/RWFBB-23.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.3)  OPEN(N,FILE='DAT/RWFBB-34.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.4)  OPEN(N,FILE='DAT/RWFBB-45.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.5)  OPEN(N,FILE='DAT/RWFBB-56.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.6)  OPEN(N,FILE='DAT/RWFBB-67.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.7)  OPEN(N,FILE='DAT/RWFBB-78.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.8)  OPEN(N,FILE='DAT/RWFBB-89.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.9)  OPEN(N,FILE='DAT/RWFBB-910.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.10) OPEN(N,FILE='DAT/RWFBB-1011.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.11) OPEN(N,FILE='DAT/RWFBB-1112.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.12) OPEN(N,FILE='DAT/RWFBB-1213.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.13) OPEN(N,FILE='DAT/RWFBB-1314.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

   ENDIF

   RETURN

 END SUBROUTINE RWFBBFILE
!!!##############################################################
      SUBROUTINE HWF2EFILE(N, L)
       IMPLICIT NONE
       INTEGER N,L

      IF(L.GT.14) THEN

         WRITE(*,*) '# hwf2efile::               L> 14. STOP'
         WRITE(*,*) '# hwf2efile::                      L = ',L
         STOP

      ELSE

         WRITE(*,*) '# hwf2e::                         L = ', L

      ENDIF
         
      IF(L.EQ.0) OPEN(UNIT=N,FILE='dat/wf2e-0.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.1) OPEN(N,FILE='dat/wf2e-1.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.2) OPEN(N,FILE='dat/wf2e-2.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.3) OPEN(N,FILE='dat/wf2e-3.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.4) OPEN(N,FILE='dat/wf2e-4.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.5) OPEN(N,FILE='dat/wf2e-5.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.6) OPEN(N,FILE='dat/wf2e-6.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.7) OPEN(N,FILE='dat/wf2e-7.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.8) OPEN(N,FILE='dat/wf2e-8.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.9) OPEN(N,FILE='dat/wf2e-9.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.10) OPEN(N,FILE='dat/wf2e-10.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.11) OPEN(N,FILE='dat/wf2e-11.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.12) OPEN(N,FILE='dat/wf2e-12.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.13) OPEN(N,FILE='dat/wf2e-13.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.14) OPEN(N,FILE='dat/wf2e-14.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      RETURN
    END SUBROUTINE HWF2EFILE

!!#######################################################################

      SUBROUTINE HDMX1EFILE(N, L, MODE)
        IMPLICIT NONE
        INTEGER N, L,MODE

        IF(L.GT.14) THEN

         WRITE(*,*) '# hdmx1efile ::               L > 14. STOP'
         WRITE(*,*) '# hdmx1efile ::                       L = ',L 
         STOP

      ELSE

         WRITE(*,*) '# hdmx1efile::                      L = ', L

      ENDIF

      IF(MODE.EQ.0) THEN 

         
      IF(L.EQ.0) OPEN(N,FILE='dat/dmx1e-01.v.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.1) OPEN(N,FILE='dat/dmx1e-12.v.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.2) OPEN(N,FILE='dat/dmx1e-23.v.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.3) OPEN(N,FILE='dat/dmx1e-34.v.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.4) OPEN(N,FILE='dat/dmx1e-45.v.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.5) OPEN(N,FILE='dat/dmx1e-56.v.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.6) OPEN(N,FILE='dat/dmx1e-67.v.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.7) OPEN(N,FILE='dat/dmx1e-78.v.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.8) OPEN(N,FILE='dat/dmx1e-89.v.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.9) OPEN(N,FILE='dat/dmx1e-910.v.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.10) OPEN(N,FILE='dat/dmx1e-1011.v.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.11) OPEN(N,FILE='dat/dmx1e-1112.v.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.12) OPEN(N,FILE='dat/dmx1e-1213.v.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.13) OPEN(N,FILE='dat/dmx1e-1314.v.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.14) OPEN(N,FILE='dat/dmx1e-1415.v.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      ELSE

      IF(L.EQ.0) OPEN(N,FILE='dat/dmx1e-01.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.1) OPEN(N,FILE='dat/dmx1e-12.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.2) OPEN(N,FILE='dat/dmx1e-23.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.3) OPEN(N,FILE='dat/dmx1e-34.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.4) OPEN(N,FILE='dat/dmx1e-45.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.5) OPEN(N,FILE='dat/dmx1e-56.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.6) OPEN(N,FILE='dat/dmx1e-67.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.7) OPEN(N,FILE='dat/dmx1e-78.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.8) OPEN(N,FILE='dat/dmx1e-89.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.9) OPEN(N,FILE='dat/dmx1e-910.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.10) OPEN(N,FILE='dat/dmx1e-1011.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.11) OPEN(N,FILE='dat/dmx1e-1112.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.12) OPEN(N,FILE='dat/dmx1e-1213.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.13) OPEN(N,FILE='dat/dmx1e-1314.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.14) OPEN(N,FILE='dat/dmx1e-1415.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      ENDIF

      RETURN
    END SUBROUTINE HDMX1EFILE

!!!##########################################################
      SUBROUTINE BFHDMX2EFILE(N, L1, L2, MODE)
        IMPLICIT NONE
        INTEGER N,L1,L2,MODE

      IF(L1.GT.14) THEN

         WRITE(*,*) '# bfhdmx2e ::           L1,L2 > 14. STOP'
         WRITE(*,*) '# bfhdmx2e ::                      L1 = ',L1 
         WRITE(*,*) '# bfhdmx2e ::                      L2 = ',L2 
         STOP

      ELSE

         IF(MODE.EQ.0) THEN

            WRITE(*,*) '# bfhdmx2e:: D_IF(J) = < I, L | D_v | F_J, L+1 > :', L1, L2
         ELSE

            WRITE(*,*) '# bfhdmx2e:: D_IF(J) = < I, L | D_l | F_J J, L+1 > :', L1, L2
         END IF
            
      ENDIF

      IF(MODE.EQ.0) THEN

      IF(L1.EQ.0.AND.L2.EQ.1) OPEN(N,FILE='DAT/HDMX2EBF-01.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.1.AND.L2.EQ.0) OPEN(N,FILE='DAT/HDMX2EBF-10.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.1.AND.L2.EQ.2) OPEN(N,FILE='DAT/HDMX2EBF-12.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.2.AND.L2.EQ.1) OPEN(N,FILE='DAT/HDMX2EBF-21.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.2.AND.L2.EQ.3) OPEN(N,FILE='DAT/HDMX2EBF-23.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.3.AND.L2.EQ.2) OPEN(N,FILE='DAT/HDMX2EBF-32.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.3.AND.L2.EQ.4)  OPEN(N,FILE='DAT/HDMX2EBF-34.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.4.AND.L2.EQ.3)  OPEN(N,FILE='DAT/HDMX2EBF-43.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.4.AND.L2.EQ.5)  OPEN(N,FILE='DAT/HDMX2EBF-45.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.5.AND.L2.EQ.4)  OPEN(N,FILE='DAT/HDMX2EBF-54.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.5.AND.L2.EQ.6)  OPEN(N,FILE='DAT/HDMX2EBF-56.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.6.AND.L2.EQ.5)  OPEN(N,FILE='DAT/HDMX2EBF-65.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.6.AND.L2.EQ.7)  OPEN(N,FILE='DAT/HDMX2EBF-67.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.7.AND.L2.EQ.6)  OPEN(N,FILE='DAT/HDMX2EBF-76.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.7.AND.L2.EQ.8)  OPEN(N,FILE='DAT/HDMX2EBF-78.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.8.AND.L2.EQ.7)  OPEN(N,FILE='DAT/HDMX2EBF-87.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.8.AND.L2.EQ.9)  OPEN(N,FILE='DAT/HDMX2EBF-89.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.9.AND.L2.EQ.8)  OPEN(N,FILE='DAT/HDMX2EBF-98.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.9.AND.L2.EQ.10) OPEN(N,FILE='DAT/HDMX2EBF-910.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.10.AND.L2.EQ.9) OPEN(N,FILE='DAT/HDMX2EBF-109.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.10.AND.L2.EQ.11) OPEN(N,FILE='DAT/HDMX2EBF-1011.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.11.AND.L2.EQ.10) OPEN(N,FILE='DAT/HDMX2EBF-1110.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.11.AND.L2.EQ.12) OPEN(N,FILE='DAT/HDMX2EBF-1112.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.12.AND.L2.EQ.11) OPEN(N,FILE='DAT/HDMX2EBF-1211.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.12.AND.L2.EQ.13) OPEN(N,FILE='DAT/HDMX2EBF-1213.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.13.AND.L2.EQ.12) OPEN(N,FILE='DAT/HDMX2EBF-1312.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.13.AND.L2.EQ.14) OPEN(N,FILE='DAT/HDMX2EBF-1314.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.4.AND.L2.EQ.13)  OPEN(N,FILE='DAT/HDMX2EBF-1415.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      ELSE
         
      IF(L1.EQ.0.AND.L2.EQ.1) OPEN(N,FILE='DAT/HDMX2EBF-01.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.1.AND.L2.EQ.0) OPEN(N,FILE='DAT/HDMX2EBF-10.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.1.AND.L2.EQ.2) OPEN(N,FILE='DAT/HDMX2EBF-12.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.2.AND.L2.EQ.1) OPEN(N,FILE='DAT/HDMX2EBF-21.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.2.AND.L2.EQ.3) OPEN(N,FILE='DAT/HDMX2EBF-23.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.3.AND.L2.EQ.2) OPEN(N,FILE='DAT/HDMX2EBF-32.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.3.AND.L2.EQ.4)   OPEN(N,FILE='DAT/HDMX2EBF-34.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.4.AND.L2.EQ.3)   OPEN(N,FILE='DAT/HDMX2EBF-43.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.4.AND.L2.EQ.5)   OPEN(N,FILE='DAT/HDMX2EBF-45.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.5.AND.L2.EQ.4)   OPEN(N,FILE='DAT/HDMX2EBF-54.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.5.AND.L2.EQ.6)   OPEN(N,FILE='DAT/HDMX2EBF-56.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.6.AND.L2.EQ.5)   OPEN(N,FILE='DAT/HDMX2EBF-65.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.6.AND.L2.EQ.7)   OPEN(N,FILE='DAT/HDMX2EBF-67.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.7.AND.L2.EQ.6)   OPEN(N,FILE='DAT/HDMX2EBF-76.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.7.AND.L2.EQ.8)   OPEN(N,FILE='DAT/HDMX2EBF-78.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.8.AND.L2.EQ.7)   OPEN(N,FILE='DAT/HDMX2EBF-87.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.8.AND.L2.EQ.9)   OPEN(N,FILE='DAT/HDMX2EBF-89.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.9.AND.L2.EQ.8)   OPEN(N,FILE='DAT/HDMX2EBF-98.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.9.AND.L2.EQ.10)  OPEN(N,FILE='DAT/HDMX2EBF-910.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.10.AND.L2.EQ.9)  OPEN(N,FILE='DAT/HDMX2EBF-109.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.10.AND.L2.EQ.11) OPEN(N,FILE='DAT/HDMX2EBF-1011.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.11.AND.L2.EQ.10) OPEN(N,FILE='DAT/HDMX2EBF-1110.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.11.AND.L2.EQ.12) OPEN(N,FILE='DAT/HDMX2EBF-1112.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.12.AND.L2.EQ.11) OPEN(N,FILE='DAT/HDMX2EBF-1211.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.12.AND.L2.EQ.13) OPEN(N,FILE='DAT/HDMX2EBF-1213.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.13.AND.L2.EQ.12) OPEN(N,FILE='DAT/HDMX2EBF-1312.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.13.AND.L2.EQ.14) OPEN(N,FILE='DAT/HDMX2EBF-1314.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.4.AND.L2.EQ.13)  OPEN(N,FILE='DAT/HDMX2EBF-1415.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

   ENDIF

   RETURN

 END SUBROUTINE BFHDMX2EFILE
!!!##########################################################
 SUBROUTINE BFDMX2EFILE(N, L1, L2, MODE)
   IMPLICIT NONE
   INTEGER N,L1,L2,MODE
   
   IF(L1.GT.14) THEN

      WRITE(*,*) ' L MUST BE LESS OR EQUAL 14  . FOR L > 14'&
           &' MODIFY SUBROUTINE CS2PHFILE. EXITING...'
      STOP
         
   ELSE

      IF(MODE.EQ.0) THEN
            
            WRITE(*,*) '# bfdmx2e:: D_IF(J) = < I, L | D_v | F_J, L+1 >:', L1, L2
         ELSE

            WRITE(*,*) '# bfdmx2e:: D_IF(j) = < I, L | D_l | F_J J, L+1 >:', L1, L2
         END IF

      ENDIF

      IF(MODE.EQ.0) THEN

      IF(L1.EQ.0.AND.L2.EQ.1) OPEN(N,FILE='DAT/DMX2EBF-01.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.1.AND.L2.EQ.0) OPEN(N,FILE='DAT/DMX2EBF-10.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.1.AND.L2.EQ.2) OPEN(N,FILE='DAT/DMX2EBF-12.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.2.AND.L2.EQ.1) OPEN(N,FILE='DAT/DMX2EBF-21.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.2.AND.L2.EQ.3) OPEN(N,FILE='DAT/DMX2EBF-23.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.3.AND.L2.EQ.2) OPEN(N,FILE='DAT/DMX2EBF-32.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.3.AND.L2.EQ.4)  OPEN(N,FILE='DAT/DMX2EBF-34.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.4.AND.L2.EQ.3)  OPEN(N,FILE='DAT/DMX2EBF-43.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.4.AND.L2.EQ.5)  OPEN(N,FILE='DAT/DMX2EBF-45.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.5.AND.L2.EQ.4)  OPEN(N,FILE='DAT/DMX2EBF-54.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.5.AND.L2.EQ.6)  OPEN(N,FILE='DAT/DMX2EBF-56.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.6.AND.L2.EQ.5)  OPEN(N,FILE='DAT/DMX2EBF-65.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.6.AND.L2.EQ.7)  OPEN(N,FILE='DAT/DMX2EBF-67.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.7.AND.L2.EQ.6)  OPEN(N,FILE='DAT/DMX2EBF-76.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.7.AND.L2.EQ.8)  OPEN(N,FILE='DAT/DMX2EBF-78.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.8.AND.L2.EQ.7)  OPEN(N,FILE='DAT/DMX2EBF-87.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.8.AND.L2.EQ.9)  OPEN(N,FILE='DAT/DMX2EBF-89.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.9.AND.L2.EQ.8)  OPEN(N,FILE='DAT/DMX2EBF-98.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.9.AND.L2.EQ.10) OPEN(N,FILE='DAT/DMX2EBF-910.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.10.AND.L2.EQ.9) OPEN(N,FILE='DAT/DMX2EBF-109.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.10.AND.L2.EQ.11) OPEN(N,FILE='DAT/DMX2EBF-1011.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.11.AND.L2.EQ.10) OPEN(N,FILE='DAT/DMX2EBF-1110.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.11.AND.L2.EQ.12) OPEN(N,FILE='DAT/DMX2EBF-1112.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.12.AND.L2.EQ.11) OPEN(N,FILE='DAT/DMX2EBF-1211.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.12.AND.L2.EQ.13) OPEN(N,FILE='DAT/DMX2EBF-1213.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.13.AND.L2.EQ.12) OPEN(N,FILE='DAT/DMX2EBF-1312.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.13.AND.L2.EQ.14) OPEN(N,FILE='DAT/DMX2EBF-1314.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.4.AND.L2.EQ.13)  OPEN(N,FILE='DAT/DMX2EBF-1415.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      ELSE
         
      IF(L1.EQ.0.AND.L2.EQ.1) OPEN(N,FILE='DAT/DMX2EBF-01.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.1.AND.L2.EQ.0) OPEN(N,FILE='DAT/DMX2EBF-10.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.1.AND.L2.EQ.2) OPEN(N,FILE='DAT/DMX2EBF-12.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.2.AND.L2.EQ.1) OPEN(N,FILE='DAT/DMX2EBF-21.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.2.AND.L2.EQ.3) OPEN(N,FILE='DAT/DMX2EBF-23.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.3.AND.L2.EQ.2) OPEN(N,FILE='DAT/DMX2EBF-32.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.3.AND.L2.EQ.4)   OPEN(N,FILE='DAT/DMX2EBF-34.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.4.AND.L2.EQ.3)   OPEN(N,FILE='DAT/DMX2EBF-43.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.4.AND.L2.EQ.5)   OPEN(N,FILE='DAT/DMX2EBF-45.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.5.AND.L2.EQ.4)   OPEN(N,FILE='DAT/DMX2EBF-54.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.5.AND.L2.EQ.6)   OPEN(N,FILE='DAT/DMX2EBF-56.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.6.AND.L2.EQ.5)   OPEN(N,FILE='DAT/DMX2EBF-65.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.6.AND.L2.EQ.7)   OPEN(N,FILE='DAT/DMX2EBF-67.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.7.AND.L2.EQ.6)   OPEN(N,FILE='DAT/DMX2EBF-76.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.7.AND.L2.EQ.8)   OPEN(N,FILE='DAT/DMX2EBF-78.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.8.AND.L2.EQ.7)   OPEN(N,FILE='DAT/DMX2EBF-87.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.8.AND.L2.EQ.9)   OPEN(N,FILE='DAT/DMX2EBF-89.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.9.AND.L2.EQ.8)   OPEN(N,FILE='DAT/DMX2EBF-98.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.9.AND.L2.EQ.10)  OPEN(N,FILE='DAT/DMX2EBF-910.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.10.AND.L2.EQ.9)  OPEN(N,FILE='DAT/DMX2EBF-109.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.10.AND.L2.EQ.11) OPEN(N,FILE='DAT/DMX2EBF-1011.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.11.AND.L2.EQ.10) OPEN(N,FILE='DAT/DMX2EBF-1110.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.11.AND.L2.EQ.12) OPEN(N,FILE='DAT/DMX2EBF-1112.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.12.AND.L2.EQ.11) OPEN(N,FILE='DAT/DMX2EBF-1211.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.12.AND.L2.EQ.13) OPEN(N,FILE='DAT/DMX2EBF-1213.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.13.AND.L2.EQ.12) OPEN(N,FILE='DAT/DMX2EBF-1312.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.13.AND.L2.EQ.14) OPEN(N,FILE='DAT/DMX2EBF-1314.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.4.AND.L2.EQ.13)  OPEN(N,FILE='DAT/DMX2EBF-1415.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

   ENDIF

   RETURN

 END SUBROUTINE BFDMX2EFILE
!!!##########################################################
 SUBROUTINE FFHDMX2EFILE(N, L1, L2, MODE)

   IMPLICIT NONE
   INTEGER N,L1,L2,MODE

   IF(L1.GT.14) THEN

      WRITE(*,*) ' L MUST BE LESS OR EQUAL 14  . FOR L > 14'&
           &' MODIFY SUBROUTINE CS2PHFILE. EXITING...'
      STOP

      ELSE

         IF(MODE.EQ.0) THEN

            WRITE(*,*) '# ffhdmx2e:: D_IF(J) = < I, L | D_v | F_J, L+1 > :', L1, L2
         ELSE

            WRITE(*,*) '# ffhdmx2e:: D_IF(J) = < I, L | D_l | F_J, L+1 > :', L1, L2
         END IF
            
      ENDIF

      IF(MODE.EQ.0) THEN

      IF(L1.EQ.0.AND.L2.EQ.1) OPEN(N,FILE='DAT/HDMX2EFF-01.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.1.AND.L2.EQ.0) OPEN(N,FILE='DAT/HDMX2EFF-10.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.1.AND.L2.EQ.2) OPEN(N,FILE='DAT/HDMX2EFF-12.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.2.AND.L2.EQ.1) OPEN(N,FILE='DAT/HDMX2EFF-21.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.2.AND.L2.EQ.3) OPEN(N,FILE='DAT/HDMX2EFF-23.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.3.AND.L2.EQ.2) OPEN(N,FILE='DAT/HDMX2EFF-32.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.3.AND.L2.EQ.4)  OPEN(N,FILE='DAT/HDMX2EFF-34.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.4.AND.L2.EQ.3)  OPEN(N,FILE='DAT/HDMX2EFF-43.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.4.AND.L2.EQ.5)  OPEN(N,FILE='DAT/HDMX2EFF-45.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.5.AND.L2.EQ.4)  OPEN(N,FILE='DAT/HDMX2EFF-54.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.5.AND.L2.EQ.6)  OPEN(N,FILE='DAT/HDMX2EFF-56.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.6.AND.L2.EQ.5)  OPEN(N,FILE='DAT/HDMX2EFF-65.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.6.AND.L2.EQ.7)  OPEN(N,FILE='DAT/HDMX2EFF-67.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.7.AND.L2.EQ.6)  OPEN(N,FILE='DAT/HDMX2EFF-76.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.7.AND.L2.EQ.8)  OPEN(N,FILE='DAT/HDMX2EFF-78.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.8.AND.L2.EQ.7)  OPEN(N,FILE='DAT/HDMX2EFF-87.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.8.AND.L2.EQ.9)  OPEN(N,FILE='DAT/HDMX2EFF-89.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.9.AND.L2.EQ.8)  OPEN(N,FILE='DAT/HDMX2EFF-98.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.9.AND.L2.EQ.10) OPEN(N,FILE='DAT/HDMX2EFF-910.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.10.AND.L2.EQ.9) OPEN(N,FILE='DAT/HDMX2EFF-109.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.10.AND.L2.EQ.11) OPEN(N,FILE='DAT/HDMX2EFF-1011.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.11.AND.L2.EQ.10) OPEN(N,FILE='DAT/HDMX2EFF-1110.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.11.AND.L2.EQ.12) OPEN(N,FILE='DAT/HDMX2EFF-1112.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.12.AND.L2.EQ.11) OPEN(N,FILE='DAT/HDMX2EFF-1211.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.12.AND.L2.EQ.13) OPEN(N,FILE='DAT/HDMX2EFF-1213.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.13.AND.L2.EQ.12) OPEN(N,FILE='DAT/HDMX2EFF-1312.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.13.AND.L2.EQ.14) OPEN(N,FILE='DAT/HDMX2EFF-1314.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.4.AND.L2.EQ.13)  OPEN(N,FILE='DAT/HDMX2EFF-1415.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      ELSE
         
      IF(L1.EQ.0.AND.L2.EQ.1) OPEN(N,FILE='DAT/HDMX2EFF-01.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.1.AND.L2.EQ.0) OPEN(N,FILE='DAT/HDMX2EFF-10.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.1.AND.L2.EQ.2) OPEN(N,FILE='DAT/HDMX2EFF-12.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.2.AND.L2.EQ.1) OPEN(N,FILE='DAT/HDMX2EFF-21.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.2.AND.L2.EQ.3) OPEN(N,FILE='DAT/HDMX2EFF-23.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.3.AND.L2.EQ.2) OPEN(N,FILE='DAT/HDMX2EFF-32.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.3.AND.L2.EQ.4)   OPEN(N,FILE='DAT/HDMX2EFF-34.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.4.AND.L2.EQ.3)   OPEN(N,FILE='DAT/HDMX2EFF-43.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.4.AND.L2.EQ.5)   OPEN(N,FILE='DAT/HDMX2EFF-45.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.5.AND.L2.EQ.4)   OPEN(N,FILE='DAT/HDMX2EFF-54.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.5.AND.L2.EQ.6)   OPEN(N,FILE='DAT/HDMX2EFF-56.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.6.AND.L2.EQ.5)   OPEN(N,FILE='DAT/HDMX2EFF-65.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.6.AND.L2.EQ.7)   OPEN(N,FILE='DAT/HDMX2EFF-67.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.7.AND.L2.EQ.6)   OPEN(N,FILE='DAT/HDMX2EFF-76.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.7.AND.L2.EQ.8)   OPEN(N,FILE='DAT/HDMX2EFF-78.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.8.AND.L2.EQ.7)   OPEN(N,FILE='DAT/HDMX2EFF-87.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.8.AND.L2.EQ.9)   OPEN(N,FILE='DAT/HDMX2EFF-89.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.9.AND.L2.EQ.8)   OPEN(N,FILE='DAT/HDMX2EFF-98.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.9.AND.L2.EQ.10)  OPEN(N,FILE='DAT/HDMX2EFF-910.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.10.AND.L2.EQ.9)  OPEN(N,FILE='DAT/HDMX2EFF-109.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.10.AND.L2.EQ.11) OPEN(N,FILE='DAT/HDMX2EFF-1011.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.11.AND.L2.EQ.10) OPEN(N,FILE='DAT/HDMX2EFF-1110.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.11.AND.L2.EQ.12) OPEN(N,FILE='DAT/HDMX2EFF-1112.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.12.AND.L2.EQ.11) OPEN(N,FILE='DAT/HDMX2EFF-1211.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.12.AND.L2.EQ.13) OPEN(N,FILE='DAT/HDMX2EFF-1213.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.13.AND.L2.EQ.12) OPEN(N,FILE='DAT/HDMX2EFF-1312.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.13.AND.L2.EQ.14) OPEN(N,FILE='DAT/HDMX2EFF-1314.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.4.AND.L2.EQ.13)  OPEN(N,FILE='DAT/HDMX2EFF-1415.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

   ENDIF

   RETURN

 END SUBROUTINE FFHDMX2EFILE
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!111
 SUBROUTINE FFDMX2EFILE(N, L1, L2, MODE)
   IMPLICIT NONE
   INTEGER N,L1,L2,MODE
   
   IF(L1.GT.14) THEN

      WRITE(*,*) ' L MUST BE LESS OR EQUAL 14  . FOR L > 14'&
           &' MODIFY SUBROUTINE CS2PHFILE. EXITING...'
      STOP
         
   ELSE

      IF(MODE.EQ.0) THEN
            WRITE(*,*) '# ffdmx2e:: D_IF(J) = < I, L | D_v | F_J, L+1 > :', L1, L2
         ELSE
            WRITE(*,*) '# ffdmx2e:: D_IF(j) = < I, L | D_l | F_J, L+1 > :', L1, L2
         END IF

      ENDIF

      IF(MODE.EQ.0) THEN

      IF(L1.EQ.0.AND.L2.EQ.1) OPEN(N,FILE='DAT/DMX2EFF-01.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.1.AND.L2.EQ.0) OPEN(N,FILE='DAT/DMX2EFF-10.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.1.AND.L2.EQ.2) OPEN(N,FILE='DAT/DMX2EFF-12.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.2.AND.L2.EQ.1) OPEN(N,FILE='DAT/DMX2EFF-21.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.2.AND.L2.EQ.3) OPEN(N,FILE='DAT/DMX2EFF-23.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.3.AND.L2.EQ.2) OPEN(N,FILE='DAT/DMX2EFF-32.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.3.AND.L2.EQ.4)  OPEN(N,FILE='DAT/DMX2EFF-34.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.4.AND.L2.EQ.3)  OPEN(N,FILE='DAT/DMX2EFF-43.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.4.AND.L2.EQ.5)  OPEN(N,FILE='DAT/DMX2EFF-45.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.5.AND.L2.EQ.4)  OPEN(N,FILE='DAT/DMX2EFF-54.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.5.AND.L2.EQ.6)  OPEN(N,FILE='DAT/DMX2EFF-56.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.6.AND.L2.EQ.5)  OPEN(N,FILE='DAT/DMX2EFF-65.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.6.AND.L2.EQ.7)  OPEN(N,FILE='DAT/DMX2EFF-67.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.7.AND.L2.EQ.6)  OPEN(N,FILE='DAT/DMX2EFF-76.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.7.AND.L2.EQ.8)  OPEN(N,FILE='DAT/DMX2EFF-78.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.8.AND.L2.EQ.7)  OPEN(N,FILE='DAT/DMX2EFF-87.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.8.AND.L2.EQ.9)  OPEN(N,FILE='DAT/DMX2EFF-89.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.9.AND.L2.EQ.8)  OPEN(N,FILE='DAT/DMX2EFF-98.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.9.AND.L2.EQ.10) OPEN(N,FILE='DAT/DMX2EFF-910.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.10.AND.L2.EQ.9) OPEN(N,FILE='DAT/DMX2EFF-109.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.10.AND.L2.EQ.11) OPEN(N,FILE='DAT/DMX2EFF-1011.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.11.AND.L2.EQ.10) OPEN(N,FILE='DAT/DMX2EFF-1110.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.11.AND.L2.EQ.12) OPEN(N,FILE='DAT/DMX2EFF-1112.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.12.AND.L2.EQ.11) OPEN(N,FILE='DAT/DMX2EFF-1211.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.12.AND.L2.EQ.13) OPEN(N,FILE='DAT/DMX2EFF-1213.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.13.AND.L2.EQ.12) OPEN(N,FILE='DAT/DMX2EFF-1312.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.13.AND.L2.EQ.14) OPEN(N,FILE='DAT/DMX2EFF-1314.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.4.AND.L2.EQ.13)  OPEN(N,FILE='DAT/DMX2EFF-1415.V.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      ELSE
         
      IF(L1.EQ.0.AND.L2.EQ.1) OPEN(N,FILE='DAT/DMX2EFF-01.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.1.AND.L2.EQ.0) OPEN(N,FILE='DAT/DMX2EFF-10.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.1.AND.L2.EQ.2) OPEN(N,FILE='DAT/DMX2EFF-12.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.2.AND.L2.EQ.1) OPEN(N,FILE='DAT/DMX2EFF-21.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.2.AND.L2.EQ.3) OPEN(N,FILE='DAT/DMX2EFF-23.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.3.AND.L2.EQ.2) OPEN(N,FILE='DAT/DMX2EFF-32.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.3.AND.L2.EQ.4)   OPEN(N,FILE='DAT/DMX2EFF-34.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.4.AND.L2.EQ.3)   OPEN(N,FILE='DAT/DMX2EFF-43.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.4.AND.L2.EQ.5)   OPEN(N,FILE='DAT/DMX2EFF-45.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.5.AND.L2.EQ.4)   OPEN(N,FILE='DAT/DMX2EFF-54.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.5.AND.L2.EQ.6)   OPEN(N,FILE='DAT/DMX2EFF-56.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.6.AND.L2.EQ.5)   OPEN(N,FILE='DAT/DMX2EFF-65.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.6.AND.L2.EQ.7)   OPEN(N,FILE='DAT/DMX2EFF-67.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.7.AND.L2.EQ.6)   OPEN(N,FILE='DAT/DMX2EFF-76.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.7.AND.L2.EQ.8)   OPEN(N,FILE='DAT/DMX2EFF-78.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.8.AND.L2.EQ.7)   OPEN(N,FILE='DAT/DMX2EFF-87.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.8.AND.L2.EQ.9)   OPEN(N,FILE='DAT/DMX2EFF-89.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.9.AND.L2.EQ.8)   OPEN(N,FILE='DAT/DMX2EFF-98.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.9.AND.L2.EQ.10)  OPEN(N,FILE='DAT/DMX2EFF-910.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.10.AND.L2.EQ.9)  OPEN(N,FILE='DAT/DMX2EFF-109.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.10.AND.L2.EQ.11) OPEN(N,FILE='DAT/DMX2EFF-1011.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.11.AND.L2.EQ.10) OPEN(N,FILE='DAT/DMX2EFF-1110.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.11.AND.L2.EQ.12) OPEN(N,FILE='DAT/DMX2EFF-1112.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.12.AND.L2.EQ.11) OPEN(N,FILE='DAT/DMX2EFF-1211.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.12.AND.L2.EQ.13) OPEN(N,FILE='DAT/DMX2EFF-1213.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.13.AND.L2.EQ.12) OPEN(N,FILE='DAT/DMX2EFF-1312.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

      IF(L1.EQ.13.AND.L2.EQ.14) OPEN(N,FILE='DAT/DMX2EFF-1314.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L1.EQ.4.AND.L2.EQ.13)  OPEN(N,FILE='DAT/DMX2EFF-1415.L.DAT', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')

   ENDIF

   RETURN

 END SUBROUTINE FFDMX2EFILE
!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 SUBROUTINE BBDMX2EFILE(N, L, MODE)

   IMPLICIT NONE
   INTEGER MODE, N,L

   IF(L.GT.14) THEN

      WRITE(*,*) ' L MUST BE LESS THAN 14 . FOR L > 14', &
           &       ' MODIFY SUBROUTINE DMX2EFILE. EXITING...'
      STOP

   ELSE

      WRITE(*,*) '# bbdmx2efile::                         L = ', L

   ENDIF
         
   IF(MODE.EQ.0) THEN

      IF(L.EQ.0) OPEN(N,FILE='dat/dmx2e-01.v.dat',FORM ='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.1) OPEN(N,FILE='dat/dmx2e-12.v.dat',FORM ='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.2) OPEN(N,FILE='dat/dmx2e-23.v.dat',FORM ='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.3) OPEN(N,FILE='dat/dmx2e-34.v.dat',FORM ='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.4) OPEN(N,FILE='dat/dmx2e-45.v.dat',FORM ='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.5) OPEN(N,FILE='dat/dmx2e-56.v.dat',FORM ='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.6) OPEN(N,FILE='dat/dmx2e-67.v.dat',FORM ='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.7) OPEN(N,FILE='dat/dmx2e-78.v.dat',FORM ='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.8) OPEN(N,FILE='dat/dmx2e-89.v.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.9) OPEN(N,FILE='dat/dmx2e-910.v.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.10) OPEN(N,FILE='dat/dmx2e-1011.v.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.11) OPEN(N,FILE='dat/dmx2e-1112.v.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.12) OPEN(N,FILE='dat/dmx2e-1213.v.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.13) OPEN(N,FILE='dat/dmx2e-1314.v.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      IF(L.EQ.14) OPEN(N,FILE='dat/dmx2e-1415.v.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
      
      ELSE
         
         IF(L.EQ.0) OPEN(N,FILE='dat/dmx2e-01.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
         IF(L.EQ.1) OPEN(N,FILE='dat/dmx2e-12.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
         IF(L.EQ.2) OPEN(N,FILE='dat/dmx2e-23.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
         IF(L.EQ.3) OPEN(N,FILE='dat/dmx2e-34.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
         IF(L.EQ.4) OPEN(N,FILE='dat/dmx2e-45.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
         IF(L.EQ.5) OPEN(N,FILE='dat/dmx2e-56.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
         IF(L.EQ.6) OPEN(N,FILE='dat/dmx2e-67.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
         IF(L.EQ.7) OPEN(N,FILE='dat/dmx2e-78.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
         IF(L.EQ.8) OPEN(N,FILE='dat/dmx2e-89.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
         IF(L.EQ.9) OPEN(N,FILE='dat/dmx2e-910.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
         IF(L.EQ.10) OPEN(N,FILE='dat/dmx2e-1011.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
         IF(L.EQ.11) OPEN(N,FILE='dat/dmx2e-1112.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
         IF(L.EQ.12) OPEN(N,FILE='dat/dmx2e-1213.l.dat', FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
         IF(L.EQ.13) OPEN(N,FILE='dat/dmx2e-1314.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
         IF(L.EQ.14) OPEN(N,FILE='dat/dmx2e-1415.l.dat',FORM='UNFORMATTED',ACCESS='SEQUENTIAL')
         
      ENDIF
      
      RETURN
    END SUBROUTINE BBDMX2EFILE

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    SUBROUTINE CS1PH2EFILE(N, L1, L2, MODE)
        IMPLICIT NONE
        INTEGER N,L1,L2,MODE

      IF(L1.GT.5) THEN

         WRITE(*,*) ' L MUST BE LESS OR EQUAL 5  . FOR L > 14'&
            &' MODIFY SUBROUTINE CS2PHFILE. EXITING...'
         STOP

      ELSE

         IF(MODE.EQ.0) THEN

            WRITE(*,*) '# cs1ph2efile ::   velocity cs1ph', L1, L2
         ELSE
            WRITE(*,*) '# cs1ph2efile ::   length   cs1ph', L1, L2

         END IF
            
      ENDIF

      IF(MODE.EQ.0) THEN

         IF(L1.EQ.0.AND.L2.EQ.1) OPEN(N,FILE='DAT/CS1PH-01.V.DAT')
         IF(L1.EQ.1.AND.L2.EQ.0) OPEN(N,FILE='DAT/CS1PH-10.V.DAT')
         IF(L1.EQ.1.AND.L2.EQ.2) OPEN(N,FILE='DAT/CS1PH-12.V.DAT')
         IF(L1.EQ.2.AND.L2.EQ.1) OPEN(N,FILE='DAT/CS1PH-21.V.DAT')
         IF(L1.EQ.2.AND.L2.EQ.3) OPEN(N,FILE='DAT/CS1PH-23.V.DAT')
         IF(L1.EQ.3.AND.L2.EQ.2) OPEN(N,FILE='DAT/CS1PH-32.V.DAT')
         IF(L1.EQ.3.AND.L2.EQ.4) OPEN(N,FILE='DAT/CS1PH-34.V.DAT')
         IF(L1.EQ.4.AND.L2.EQ.3) OPEN(N,FILE='DAT/CS1PH-43.V.DAT')
         IF(L1.EQ.4.AND.L2.EQ.5) OPEN(N,FILE='DAT/CS1PH-45.V.DAT')
         IF(L1.EQ.5.AND.L2.EQ.4) OPEN(N,FILE='DAT/CS1PH-54.V.DAT')


      ELSE

         IF(L1.EQ.0.AND.L2.EQ.1) OPEN(N,FILE='DAT/CS1PH-01.L.DAT')
         IF(L1.EQ.1.AND.L2.EQ.0) OPEN(N,FILE='DAT/CS1PH-10.L.DAT')
         IF(L1.EQ.1.AND.L2.EQ.2) OPEN(N,FILE='DAT/CS1PH-12.L.DAT')
         IF(L1.EQ.2.AND.L2.EQ.1) OPEN(N,FILE='DAT/CS1PH-21.L.DAT')
         IF(L1.EQ.2.AND.L2.EQ.3) OPEN(N,FILE='DAT/CS1PH-23.L.DAT')
         IF(L1.EQ.3.AND.L2.EQ.2) OPEN(N,FILE='DAT/CS1PH-32.L.DAT')
         IF(L1.EQ.3.AND.L2.EQ.4) OPEN(N,FILE='DAT/CS1PH-34.L.DAT')
         IF(L1.EQ.4.AND.L2.EQ.3) OPEN(N,FILE='DAT/CS1PH-43.L.DAT')
         IF(L1.EQ.4.AND.L2.EQ.5) OPEN(N,FILE='DAT/CS1PH-45.L.DAT')
         IF(L1.EQ.5.AND.L2.EQ.4) OPEN(N,FILE='DAT/CS1PH-54.L.DAT')


   ENDIF

   RETURN

 END SUBROUTINE CS1PH2EFILE

!!!#######################################################################

END MODULE ioroutines
!!!##############################################################
!!!EOF
