      PARAMETER(   NS = 302,     NP = 1200,  NL = 10 )
      PARAMETER(   LF =   5,    NHX = 2500, NCS = 30 )
      PARAMETER( NL1E =  10,  NWF2E =  1800 )
c------------------------------------------------------
c NS   : max nof b-splines
c NP   : max nof integration points
c NL   : max nof 1-e partial angular momenta
c LF   : max nof 2-e partial angular momenta
c NHX  : max nof 2-e CI Hamiltonian matrix   
c NCS  : max nof configuration series
c NWF2E: max nof 2e output states       (dmx2e.f)
c NL1E : max nof 1e partial wave states (dmx2e.f)
c----------------------------------------------------
