      PARAMETER( NS = 72, NP = 1200,  NL = 5)
      PARAMETER( LF = 3,  NHX = 18050, NCS = 301, NWF2E = 4000)
c------------------------------------------------------
c NS   : max nof b-splines
c NP   : max nof integration points
c NL   : max nof 1-e partial angular momenta
c LF   : max nof 2-e partial angular momenta
c NHX  : max nof 2-e CI Hamiltonian matrix   
c NCS  : max nof configuration series
c NWF2E: max nof 2e output states       (dmx2e.f)
c NL1E : max nof 1e partial wave states (dmx2e.f)
c----------------------------------------------------
